In [1]:
import pandas as pd

In [2]:
df_clientes = pd.read_csv('customer_data.csv')

In [3]:
df_clientes.head()

  customer_id  gender   age payment_method
0     C241288  Female  28.0    Credit Card
1     C111565    Male  21.0     Debit Card
2     C266599    Male  20.0           Cash
3     C988172  Female  66.0    Credit Card
4     C189076  Female  53.0           Cash

In [4]:
df_ventas = pd.read_csv('sales_data.csv')

In [5]:
df_ventas.head()

,invoice_no,customer_id,category,quantity,price,invoice_date,shopping_mall
0,I138884,C241288,Clothing,5,1500.40,05-08-2022,Kanyon
1,I317333,C111565,Shoes,3,1800.51,12-12-2021,Forum Istanbul
2,I127801,C266599,Clothing,1,300.08,09-11-2021,Metrocity
3,I173702,C988172,Shoes,5,3000.85,16-05-2021,Metropol AVM
4,I337046,C189076,Books,4,60.60,24-10-2021,Kanyon

In [6]:
df_final = pd.merge(df_ventas, df_clientes, on='customer_id', how='left')

In [7]:
df_final.head()

,invoice_no,customer_id,category,quantity,price,invoice_date,shopping_mall,gender,age,payment_method
0,I138884,C241288,Clothing,5,1500.40,05-08-2022,Kanyon,Female,28.0,Credit Card
1,I317333,C111565,Shoes,3,1800.51,12-12-2021,Forum Istanbul,Male,21.0,Debit Card
2,I127801,C266599,Clothing,1,300.08,09-11-2021,Metrocity,Male,20.0,Cash
3,I173702,C988172,Shoes,5,3000.85,16-05-2021,Metropol AVM,Female,66.0,Credit Card
4,I337046,C189076,Books,4,60.60,24-10-2021,Kanyon,Female,53.0,Cash

In [8]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_no      99457 non-null  object
 1   customer_id     99457 non-null  object
 2   category        99457 non-null  object
 3   quantity        99457 non-null  int64
 4   price           99457 non-null  float64
 5   invoice_date    99457 non-null  object
 6   shopping_mall   99457 non-null  object
 7   gender          99457 non-null  object
 8   age             99338 non-null  float64
 9   payment_method  99457 non-null  object
dtypes: float64(2), int64(1), object(7)
memory usage: 7.6+ MB

In [9]:
#Calculo de la Media

In [10]:
media_edad = df_final['age'].mean()

In [11]:
media_edad

np.float64(43.42585918782339)

In [12]:
#Relleno de los valores nulos     para que no de float :   media_edad = int(df_final["age"].mean())    df_final["age"] = df_final["age"].fillna(media_edad)

In [13]:
df_final['age'] = df_final['age'].fillna(media_edad)

In [14]:
df_final['age'].isnull().sum()

np.int64(0)

In [15]:
#Convertir la columna de fecha a formato datetime

In [16]:
df_final['invoice_date'] = pd.to_datetime(df_final['invoice_date'],format='%d-%m-%Y',errors='coerce'  # Si alguna fecha es inválida, la convierte a NaT (Not a Time)
)

In [17]:
# Comprobar la conversion

In [18]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_no      99457 non-null  object
 1   customer_id     99457 non-null  object
 2   category        99457 non-null  object
 3   quantity        99457 non-null  int64
 4   price           99457 non-null  float64
 5   invoice_date    99457 non-null  datetime64[ns]
 6   shopping_mall   99457 non-null  object
 7   gender          99457 non-null  object
 8   age             99457 non-null  float64
 9   payment_method  99457 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(6)
memory usage: 7.6+ MB

In [19]:
# Creaciòn de grupos etarios, definiendo limites y etiquetas de cada uno

In [20]:
bins = [18, 25, 36, 50, 65, 100]
labels = ['18-24', '25-35', '36-49', '50-64', '65+']

In [21]:
df_final['age_group'] = pd.cut(
    df_final['age'],
    bins=bins,
    labels=labels,
    right=False,
    include_lowest=True
)

In [22]:
df_final[['age', 'age_group']].head(10)

    age age_group
0  28.0     25-35
1  21.0     18-24
2  20.0     18-24
3  66.0       65+
4  53.0     50-64
5  28.0     25-35
6  49.0     36-49
7  32.0     25-35
8  69.0       65+
9  60.0     50-64

In [23]:
df_final['age_group'].value_counts()

age_group
50-64    28515
36-49    27155
25-35    20893
18-24    13484
65+       9410
Name: count, dtype: int64

In [24]:
#Métodos de pago grupo etario 25-35

In [25]:
metodos_pago_25_35 = (
    df_final.loc[df_final['age_group'] == '25-35', 'payment_method']
    .value_counts()
)

In [26]:
print(metodos_pago_25_35)

payment_method
Cash           9356
Credit Card    7274
Debit Card     4263
Name: count, dtype: int64

In [27]:
#Métodos de pago grupo etario Mujeres

In [28]:
metodos_pago_mujeres = (
    df_final.loc[df_final['gender'] == 'Female', 'payment_method']
    .value_counts()
)

In [29]:
print(metodos_pago_mujeres)

payment_method
Cash           26509
Credit Card    21011
Debit Card     11962
Name: count, dtype: int64

In [30]:
# Métodos de pago mas freceunte de todos los clientes

In [31]:
moda_general = df_final['payment_method'].mode()[0]

In [32]:
print(moda_general)

Cash

In [33]:
# Mètodos de pago màs frecuente de todos los clientes, categorizados por gènero

In [34]:
moda_por_genero = df_final.groupby('gender')['payment_method'].agg(pd.Series.mode)

In [35]:
print(moda_por_genero)

gender
Female    Cash
Male      Cash
Name: payment_method, dtype: object

In [36]:
# Categorización de clientes de acuerdo a su forma de pago (por edad y por genero)

In [37]:
categorizacion = (
    df_final.groupby(['age_group', 'gender', 'payment_method'], observed=True)
    .size()
    .reset_index(name='Total_Clientes')
    .sort_values(by='Total_Clientes', ascending=False)
)

In [38]:
print(categorizacion.head(10))

   age_group  gender payment_method  Total_Clientes
18     50-64  Female           Cash            7639
12     36-49  Female           Cash            7262
19     50-64  Female    Credit Card            5995
13     36-49  Female    Credit Card            5803
6      25-35  Female           Cash            5521
21     50-64    Male           Cash            5136
15     36-49    Male           Cash            4832
7      25-35  Female    Credit Card            4401
22     50-64    Male    Credit Card            3979
9      25-35    Male           Cash            3835

In [39]:
# Precios por categoria de productos

In [40]:
analisis_precios = df_final.groupby('category')['price'].describe()

In [41]:
print(analisis_precios)

                   count         mean          std      min      25%      50%  \
category
Books             4981.0    45.568621    21.492662    15.15    30.30    45.45
Clothing         34487.0   901.084021   424.225594   300.08   600.16   900.24
Cosmetics        15097.0   122.448626    57.458097    40.66    81.32   121.98
Food & Beverage  14776.0    15.671948     7.422176     5.23    10.46    15.69
Shoes            10034.0  1807.388568   845.116269   600.17  1200.34  1800.51
Souvenir          4999.0    34.894345    16.564498    11.73    23.46    35.19
Technology        4996.0  3156.935548  1481.559805  1050.00  2100.00  3150.00
Toys             10087.0   107.733185    50.364844    35.84    71.68   107.52

                     75%      max
category
Books              60.60    75.75
Clothing         1200.32  1500.40
Cosmetics         162.64   203.30
Food & Beverage    20.92    26.15
Shoes            2400.68  3000.85
Souvenir           46.92    58.65
Technology       4200.00  5250.00
Toys              143.36   179.20

In [42]:
df_final.head()

,invoice_no,customer_id,category,quantity,price,invoice_date,shopping_mall,gender,age,payment_method,age_group
0,I138884,C241288,Clothing,5,1500.40,2022-08-05,Kanyon,Female,28.0,Credit Card,25-35
1,I317333,C111565,Shoes,3,1800.51,2021-12-12,Forum Istanbul,Male,21.0,Debit Card,18-24
2,I127801,C266599,Clothing,1,300.08,2021-11-09,Metrocity,Male,20.0,Cash,18-24
3,I173702,C988172,Shoes,5,3000.85,2021-05-16,Metropol AVM,Female,66.0,Credit Card,65+
4,I337046,C189076,Books,4,60.60,2021-10-24,Kanyon,Female,53.0,Cash,50-64

In [43]:
# Anàlisis exploratorio de datos para la extracciòn de informaciòn valiosa

In [44]:
conteo_genero_por_mall = (
    df_final.groupby(['shopping_mall', 'gender'])
    .size()
    .unstack(fill_value=0)
)

In [45]:
print(conteo_genero_por_mall)

gender             Female  Male
shopping_mall
Cevahir AVM          2940  2051
Emaar Square Mall    2842  1969
Forum Istanbul       3016  1931
Istinye Park         5874  3907
Kanyon              11906  7917
Mall of Istanbul    11902  8041
Metrocity            8941  6070
Metropol AVM         6144  4017
Viaport Outlet       2949  1965
Zorlu Center         2968  2107

In [46]:
conteo_genero_por_category = (
    df_final.groupby(['category', 'gender'])
    .size()
    .unstack(fill_value=0)
)

In [47]:
print(conteo_genero_por_category)

gender           Female   Male
category
Books              2906   2075
Clothing          20652  13835
Cosmetics          9070   6027
Food & Beverage    8804   5972
Shoes              5967   4067
Souvenir           3017   1982
Technology         2981   2015
Toys               6085   4002

In [48]:
gasto_por_segmento = (
    df_final.groupby(['gender', 'category'])['price']
    .sum()
    .reset_index(name='Gasto_Total')
    .sort_values(by='Gasto_Total', ascending=False)
)

In [49]:
print(gasto_por_segmento)

    gender         category  Gasto_Total
1   Female         Clothing  18616663.12
9     Male         Clothing  12459021.52
4   Female            Shoes  10746644.02
6   Female       Technology   9425850.00
12    Male            Shoes   7388692.87
14    Male       Technology   6346200.00
2   Female        Cosmetics   1108432.26
10    Male        Cosmetics    740174.64
7   Female             Toys    658094.08
15    Male             Toys    428610.56
3   Female  Food & Beverage    137873.26
0   Female            Books    132956.40
5   Female         Souvenir    105288.48
8     Male            Books     94020.90
11    Male  Food & Beverage     93695.45
13    Male         Souvenir     69148.35

In [50]:
moda_por_genero = df_final.groupby('gender')['payment_method'].agg(pd.Series.mode)

In [51]:
print(moda_por_genero)

gender
Female    Cash
Male      Cash
Name: payment_method, dtype: object

In [52]:
df_final['day_name'] = df_final['invoice_date'].dt.day_name()

In [53]:
ventas_por_dia = (
    df_final['invoice_date']
    .dt.day_name()
    .value_counts()
    .sort_values(ascending=False)
)

In [54]:
print(ventas_por_dia)

invoice_date
Monday       14383
Friday       14347
Tuesday      14217
Sunday       14140
Thursday     14129
Saturday     14121
Wednesday    14120
Name: count, dtype: int64

In [55]:
# 1. Extraer el nombre del mes
df_final['month_name'] = df_final['invoice_date'].dt.month_name()

In [56]:
# 2. Contar la cantidad de transacciones por mes
ventas_por_mes = df_final['month_name'].value_counts()

In [57]:
print(ventas_por_mes)

month_name
January      11608
February     10482
March         8730
July          7877
October       7764
May           7697
December      7680
August        7635
June          7581
November      7563
April         7487
September     7353
Name: count, dtype: int64

In [58]:
df_final["shopping_mall"].value_counts()  #vemos el volunen de transacciones por mall

shopping_mall
Mall of Istanbul     19943
Kanyon               19823
Metrocity            15011
Metropol AVM         10161
Istinye Park          9781
Zorlu Center          5075
Cevahir AVM           4991
Forum Istanbul        4947
Viaport Outlet        4914
Emaar Square Mall     4811
Name: count, dtype: int64

In [59]:
agrupado_mall = df_final.groupby("shopping_mall")["price"].sum() #Calcular la facturación total por shopping

In [60]:
Fact_mall = agrupado_mall.reset_index()   # creamos un dframe para operarlo

In [61]:
Fact_mall = Fact_mall.sort_values("price", ascending=False)

In [62]:
Fact_mall

       shopping_mall        price
5   Mall of Istanbul  13851737.62
4             Kanyon  13710755.24
6          Metrocity  10249980.07
7       Metropol AVM   6937992.99
3       Istinye Park   6717077.54
9       Zorlu Center   3509649.02
0        Cevahir AVM   3433671.84
8     Viaport Outlet   3414019.46
1  Emaar Square Mall   3390408.31
2     Forum Istanbul   3336073.82

In [63]:
df_final.head()

,invoice_no,customer_id,category,quantity,price,invoice_date,shopping_mall,gender,age,payment_method,age_group,day_name,month_name
0,I138884,C241288,Clothing,5,1500.40,2022-08-05,Kanyon,Female,28.0,Credit Card,25-35,Friday,August
1,I317333,C111565,Shoes,3,1800.51,2021-12-12,Forum Istanbul,Male,21.0,Debit Card,18-24,Sunday,December
2,I127801,C266599,Clothing,1,300.08,2021-11-09,Metrocity,Male,20.0,Cash,18-24,Tuesday,November
3,I173702,C988172,Shoes,5,3000.85,2021-05-16,Metropol AVM,Female,66.0,Credit Card,65+,Sunday,May
4,I337046,C189076,Books,4,60.60,2021-10-24,Kanyon,Female,53.0,Cash,50-64,Sunday,October

In [67]:
df_final.to_excel('informe_final_limpio.xlsx', index=False)

In [68]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_no      99457 non-null  object
 1   customer_id     99457 non-null  object
 2   category        99457 non-null  object
 3   quantity        99457 non-null  int64
 4   price           99457 non-null  float64
 5   invoice_date    99457 non-null  datetime64[ns]
 6   shopping_mall   99457 non-null  object
 7   gender          99457 non-null  object
 8   age             99457 non-null  float64
 9   payment_method  99457 non-null  object
 10  age_group       99457 non-null  category
 11  day_name        99457 non-null  object
 12  month_name      99457 non-null  object
dtypes: category(1), datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 9.2+ MB

In [69]:
# CARGA FINAL A MySQL

In [70]:
#Instalacion del conector de Pandas

In [71]:
!pip install sqlalchemy mysql-connector-python pymysql

Requirement already satisfied: sqlalchemy in c:\users\todop\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: mysql-connector-python in c:\users\todop\anaconda3\lib\site-packages (9.4.0)
Requirement already satisfied: pymysql in c:\users\todop\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\todop\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\todop\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)

In [72]:
# 2. Configuración de la conexión

In [73]:
import pandas as pd
from sqlalchemy import create_engine
import getpass # Para ingresar la contraseña de forma segura

# --- Variables de Conexión ---
USUARIO = 'root'      
PASSWORD = getpass.getpass('root: ') # Ingresa tu contraseña de forma segura
HOST = 'localhost'                # O la IP de tu servidor MySQL
PUERTO = 3306                     # Puerto estándar de MySQL
BASE_DE_DATOS = 'abp_datos_limpios' # Debe existir previamente en MySQL

# Crear la cadena de conexión (URL de SQLAlchemy)
# El formato es: 'dialect+driver://user:password@host:port/database'
CONN_STRING = f"mysql+pymysql://{USUARIO}:{PASSWORD}@{HOST}:{PUERTO}/{BASE_DE_DATOS}"
# Crear el motor de conexión
engine = create_engine(CONN_STRING)

print("Conexión con el motor SQLAlchemy creada.")

root:  ········

Conexión con el motor SQLAlchemy creada.

In [76]:
# Carga del DataFrame a MySQL

In [78]:
NOMBRE_TABLA = 'proyecto' # Nombre que tendrá la tabla en MySQL

try:
    df_final.to_sql(
        name=NOMBRE_TABLA, 
        con=engine, 
        if_exists='replace', # 'replace' borra y recrea la tabla si ya existe
        index=False,         # No carga el índice de Pandas como una columna
            )
    print(f"✅ ¡Carga exitosa! Datos cargados a la tabla '{NOMBRE_TABLA}' en MySQL.")
    
except Exception as e:
    print(f"❌ Error al cargar los datos: {e}")

✅ ¡Carga exitosa! Datos cargados a la tabla 'proyecto' en MySQL.